// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEXlALDgnt3Nb6jr2ZDAGtlYLY3-XXRCQ',
    appId: '1:861886020382:web:5a5fb2bdbaa59cc04e670f',
    messagingSenderId: '861886020382',
    projectId: 'project-78283',
    authDomain: 'project-78283.firebaseapp.com',
    databaseURL: 'https://project-78283-default-rtdb.firebaseio.com',
    storageBucket: 'project-78283.appspot.com',
    measurementId: 'G-VHP3EPGTL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYvwFT1Ow5RTo5d-0pK4uyojjwflBznEg',
    appId: '1:861886020382:android:3d4c3f88e8482d604e670f',
    messagingSenderId: '861886020382',
    projectId: 'project-78283',
    databaseURL: 'https://project-78283-default-rtdb.firebaseio.com',
    storageBucket: 'project-78283.appspot.com',
  );
}
